# Generated by Django 3.1.3 on 2021-01-02 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_auto_20201208_0537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='Mileage',
            new_name='mileage',
        ),
        migrations.RenameField(
            model_name='auto',
            old_name='Nickname',
            new_name='nickname',
        ),
    ]
