# Generated by Django 3.1.3 on 2021-01-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_auto_20210102_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='Foods',
            new_name='foods',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='Nickname',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='Weight',
            new_name='weight',
        ),
    ]
